name: CI - Train and Save the model

on:
  push:
    branches: [ main ]
    paths: 
      - '02-role-of-mlops/src/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - '02-role-of-mlops/src/**'
      - '.github/workflows/ci.yml'

jobs:
  matrix-pipx:
    name: CI - Train and Save the model 
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel
      
      - name: Install dependencies
        run: python -m pip install -r 02-role-of-mlops/src/requirements.txt
      
      - name: Train the model
        run: | 
            python 02-role-of-mlops/src/train.py 
            ls -la 02-role-of-mlops/src/artifacts

      - name: Upload artifcats
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts-${{ matrix.python-version }}-${{ github.run_id }}
          path: 02-role-of-mlops/src/artifacts